---
apiVersion: v1
kind: ConfigMap
metadata:
  name: counter-config
data:
  DB_HOST: counter-database
  BACKEND_URL: https://counter-backend-computerficker-dev.apps.sandbox-m3.1530.p1.openshiftapps.com
